# Generated by Django 5.0.2 on 2024-02-08 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ods',
            name='clubs',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ods',
            name='code_commune',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='ods',
            name='code_fede',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ods',
            name='code_qpv',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ods',
            name='commune',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ods',
            name='department',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='ods',
            name='epa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ods',
            name='fede',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ods',
            name='name_qpv',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ods',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ods',
            name='statut_geo',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ods',
            name='total',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ods',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 2, 8, 15, 4, 55, 361799)),
        ),
    ]
