# Generated by Django 5.0.2 on 2024-02-09 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ods_clubs_ods_code_commune_ods_code_fede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 2, 9, 8, 7, 17, 821865)),
        ),
    ]
