# Generated by Django 5.0.2 on 2024-02-09 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ods_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ods',
            old_name='fede',
            new_name='federation',
        ),
        migrations.AlterField(
            model_name='ods',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 2, 9, 8, 19, 45, 710174)),
        ),
    ]
